---    
- name: Perform Initialization
  tags: common
  hosts: vm
  tasks:
    - import_role:
        name: common

- name: Install Metrics Collector
  tags: metrics
  hosts: vm
  tasks:
    - import_role:
        name: metrics

- name: Install Container Runtime
  tags: cr
  hosts: vm
  tasks:
    - import_role:
        name: container_runtime
      when: "plex_install is not defined || plex_install != true"

- name: Install Portainer
  tags: portainer
  hosts: vm
  tasks:
    - import_role:
        name: portainer
      when: "plex_install is not defined || plex_install != true"

- name: Generate Portainer Stacks
  tags: portainer,stacks
  hosts: vm
  tasks:
    - import_role:
        name: portainer
        tasks_from: stack_generator.yaml
      when:
        - portainer_stacks is defined
        - "plex_install is not defined || plex_install != true"

- name: Install Plex
  tags: plex
  hosts: vm
  tasks:
    - import_role:
        name: plex
      when:
        - plex_install is defined 
        - plex_install == true