---
- name: Create Mountable directories
  file:
    path: "/mnt/{{ plex_storage_pathname }}/{{ item | regex_search('/mnt/([a-zA-Z0-9]+/[a-zA-Z0-9]+)','\\1') | first | lower }}"
    state: directory
  loop: "{{ plex_storage_export_paths }}"

- name: Configure Read-Only NFS Mounts
  ansible.posix.mount:
    src: "{{ plex_storage_hostname }}:{{ item }}"
    path: "/mnt/{{ plex_storage_pathname }}/{{ item | regex_search('/mnt/([a-zA-Z0-9]+/[a-zA-Z0-9]+)','\\1') | first | lower }}"
    backup: yes
    fstype: nfs
    state: mounted
    opts: "defaults,tcp,timeo=10,ro"
  loop: "{{ plex_storage_export_paths }}"